import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import vm from 'node:vm';

// Exercise saved story transitions without Three/WebGL; game rules are tested in
// the browser regression. The host below only supplies the existing DOM/game API.
const elements=new Map(),events=[],camera=[];
function node(){
  const n={children:[],dataset:{},style:{},attributes:{},hidden:false,textContent:'',classList:{add(){},remove(){},toggle(){}},setAttribute(key,value){this.attributes[key]=value},addEventListener(){},focus(){},remove(){},append(...xs){this.children.push(...xs)},replaceChildren(...xs){this.children=xs},querySelector(){return node()}};
  Object.defineProperty(n,'id',{get(){return this._id},set(id){this._id=id;elements.set(id,this)}});return n;
}
const document={body:node(),createElement:node,getElementById:id=>elements.get(id)||null,querySelector:()=>node()};
const actor={id:'hero',name:'Мира',classId:'wizard',kind:1,appearance:{gender:'female',hair:'#26282e'},background:'Ты ищешь письмо с незнакомой печатью.',x:4,y:4,max:8,hp:8,conditions:[],death:{success:0,failure:0,stable:false},hands:['staff','empty'],stats:{int:16,con:14}};
const initial=()=>({world:{gen:{v:3,seed:'test'},discovered:['glade']},scene:'glade',party:[structuredClone(actor)],active:'hero',combat:false,xp:0,gold:0,logs:[],story:{v:1,intro:0,npcWarned:false,npcDeparted:false,clues:[],cleared:[],reachedSettlement:false,reported:false}});
const plan={story:{id:'mist',title:'Туман',problem:'Туман закрывает дорогу.',arrival:'Ты выходишь на опушку.',warning:'Помогите! Туман идёт к деревне.',objective:'Найти причину и предупредить старосту.',clue:'На ленте остаётся серый налёт.',clueProp:'story-clue',clueScene:'cart',rescue:'Целитель возвращает тебя в сознание.',report:'Староста принимает найденные сведения.',messenger:{name:'Рин',full:'Рин · путник'},healer:{name:'Тея',full:'Тея · целитель'},elder:{name:'Орен',full:'Орен · староста'},tutorial:{}}};
const game={state:initial(),active(){return this.state.party[0]},scene:{id:'glade',W:16,H:14,props:[],encounters:[]},get props(){return this.scene.props},get busy(){return false},save(){},render(){},tell(t){this.state.logs.push(t)},beginEncounter:async()=>true,departNpc:async()=>true,arriveNpc:async()=>true,heal(a,n){a.hp=Math.min(a.max,a.hp+n)},blocked:()=>false};
const env={document,gameDebug:game,GeneratedWorlds:{plan},Artwork:{hero:a=>Object.assign(node(),{actor:a})},Worlds:{atMenu:false,locked:false},viewsDebug:{tab:'map',switchTab(){}},camera:{center:p=>camera.push({x:p.x,y:p.y}),zoom:n=>camera.push({zoom:n})},voxel:{sync(){}},Tutorial:{active:false,blocksPortals:false},HUD:{active:false,pending:false,check:async()=>{}},structuredClone,queueMicrotask,setTimeout,clearTimeout,CustomEvent,dispatchEvent:e=>events.push(e.detail),addEventListener(){},DND:{damage(a,n){a.hp=Math.max(0,a.hp-n);if(!a.hp)a.conditions.push('unconscious')},skill:()=>({natural:12,total:15,dc:10,success:true,text:'Расследование · 12 + 3 = 15 против 10'})}};
env.window=env;vm.createContext(env);
const file=new URL('../dist/adventure.js',import.meta.url);
if(existsSync(file))vm.runInContext(readFileSync(file,'utf8'),env);
assert.equal(typeof env.Adventure?.restore,'function','Adventure restores a saved story checkpoint');
env.Adventure.restore(game.state);
assert.equal(env.Adventure.blocksPortals,true,'Intro blocks leaving the scene');
assert.equal(game.state.party[0].appearance.hair,actor.appearance.hair,'Intro preserves the chosen appearance');
const intro=env.Adventure.introLength;
env.Adventure.nextIntro();const checkpoint=structuredClone(game.state);
game.state=checkpoint;env.Adventure.restore(game.state);
assert.equal(game.state.story.intro,1,'Reload resumes the next cinematic frame');
while(game.state.story.intro<intro)env.Adventure.nextIntro();
assert.equal(env.Adventure.visibleProp({storyRole:'messenger'}),true);
game.state.story.npcDeparted=true;
assert.equal(env.Adventure.visibleProp({storyRole:'messenger'}),false,'The departed messenger cannot return after reload');
assert.equal(env.Adventure.visibleProp({id:'legacy-npc'}),true,'Legacy props remain visible');
game.state.story.npcWarned=true;
env.Tutorial.active=false;env.Tutorial.blocksPortals=false;
assert.equal(env.Adventure.blocksPortals,false,'Completed tutorial permits continuing the story');
const encounter={id:'road-threat',scene:'road',name:'Дорожная угроза',reward:{xp:25,gold:5},tutorial:false};
game.scene.encounters=[encounter];
let triggered=null;
game.beginEncounter=async spec=>{triggered=spec.id;return true;};
assert.equal(env.Adventure.step(game.scene,4,4),false,'Distant encounters do not start');
game.scene.encounters=[{...encounter,x:4,y:4,radius:2}];
assert.equal(env.Adventure.step(game.scene,4,4),true,'Ordinary encounter triggers after the tutorial');
env.Adventure.render();await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(triggered,'road-threat','Completed tutorial never blocks ordinary encounters');
game.state.encounter=encounter;
assert.equal(env.Adventure.victory(encounter),true);
assert.deepEqual([...game.state.story.cleared],['road-threat']);
assert.equal(game.state.xp,25);assert.equal(game.state.gold,5);
env.Adventure.victory(encounter);
assert.equal(game.state.xp,25,'A cleared encounter never awards twice');
game.state.encounter={...encounter,id:'tutorial-win',tutorial:true,reward:{xp:999,gold:999}};
env.Adventure.victory(game.state.encounter);
assert.equal(game.state.xp,25,'Training cannot award permanent experience');
assert.equal(game.state.gold,5,'Training cannot award permanent gold');
game.state.encounter={id:'tutorial-loss',tutorial:true,scriptedLoss:true};
game.state.combat=true;
env.Adventure.defeatRescue();
assert.equal(game.active().hp,0);assert.equal(game.active().dead,false,'Scripted tutorial loss never kills the hero');
assert.equal(game.state.combat,false);
assert.equal(events.at(-1).type,'unconscious');
assert.equal(events.at(-1).encounterId,'tutorial-loss');
env.Adventure.restore(game.state);
assert.equal(game.active().hp,0,'Reload does not grant an early rescue or reward');
assert.equal(env.Adventure.visibleProp({storyRole:'messenger'}),false);
game.state=initial();Object.assign(game.state.story,{intro:3,npcWarned:true,npcDeparted:true});
game.state.combat=true;game.state.encounter={id:'tutorial-win',tutorial:true};game.state.enemies=[{id:'training',name:'Манекен',hp:8}];
game.canAttack=()=>true;let attacks=0;game.attack=()=>{attacks++};game.special=game.potion=game.endTurn=()=>{};
env.Adventure.restore(game.state);
const battle=elements.get('adventure-combat'),toggle=()=>battle.children.find(n=>n.className==='adventure-combat-toggle'),choices=()=>battle.children.find(n=>n.className==='adventure-battle-actions');
assert.ok(toggle(),'Prepared combat choices have an explicit compact toggle');
assert.equal(toggle().attributes['aria-expanded'],'false');assert.equal(choices().hidden,true,'Choices start collapsed so the map remains visible');
toggle().onclick();assert.equal(toggle().attributes['aria-expanded'],'true');assert.equal(choices().hidden,false);
choices().children.find(n=>n.textContent.startsWith('Атаковать:')).onclick();assert.equal(attacks,1);assert.equal(choices().hidden,true,'A selected legal action returns to the map');
toggle().onclick();game.state.encounter={id:'tutorial-loss',tutorial:true};env.Adventure.render();assert.equal(choices().hidden,true,'New encounters reset expanded choices');
toggle().onclick();env.Adventure.restore(game.state);assert.equal(choices().hidden,true,'Reload resets expanded choices');
console.log('PASS adventure client: cinematic checkpoints, own appearance, departed NPC, once-only rewards, safe tutorial unconsciousness and compact prepared combat choices');
