export const POINT_BUDGET=27;
export const POINT_COSTS={8:0,9:1,10:2,11:3,12:4,13:5,14:7,15:9};
export function pointsUsed(stats){return Object.values(stats||{}).reduce((sum,n)=>sum+(Number.isInteger(n)&&Object.hasOwn(POINT_COSTS,n)?POINT_COSTS[n]:Infinity),0);}
export function emptyStats(){return Object.fromEntries(Object.keys(LABELS).map(k=>[k,8]));}
export function adjustStat(stats,key,delta){if(!Object.hasOwn(LABELS,key)||![-1,1].includes(delta))return false;const next=stats[key]+delta;if(!Object.hasOwn(POINT_COSTS,next))return false;const updated={...stats,[key]:next};if(pointsUsed(updated)>POINT_BUDGET)return false;stats[key]=next;return true;}
export const ARRAY=[15,14,13,12,10,8];
export const LABELS={str:'Сила',dex:'Ловкость',con:'Телосложение',int:'Интеллект',wis:'Мудрость',cha:'Харизма'};
export const COLORS={skin:['#e3bb8a','#c58d64','#8b5b42','#f2d4b4'],hair:['#493024','#b7803c','#26282e','#c7c4bf','#a64f35'],cloth:['#487844','#62377e','#315e84','#843f37','#566d70'],trim:['#c3a04c','#b6bdc5','#78552e','#c5b895']};
export const CLASSES={fighter:{name:'Воин',kind:2,die:10,priority:['str','con','dex','wis','cha','int'],skills:['athletics','perception'],saves:['str','con'],hint:'Сила — удары мечом, Телосложение — здоровье.',kits:[{name:'Меч и щит',hands:['sword','shield'],armor:'Кольчуга',ac:16,weapon:'longsword',items:['Длинный меч · 1d8','Щит · +2 КД','Кольчуга','Рюкзак','Верёвка · 15 м','Рационы · 5 дней']},{name:'Походный воин',hands:['sword','shield'],armor:'Кольчуга',ac:16,weapon:'longsword',items:['Длинный меч · 1d8','Щит · +2 КД','Кольчуга','Рюкзак','Одеяло','Набор для разведения огня']}]},rogue:{name:'Плут',kind:0,die:8,priority:['dex','con','cha','wis','int','str'],skills:['stealth','investigation','perception','persuasion'],saves:['dex','int'],hint:'Ловкость — оружие, защита и скрытность.',kits:[{name:'Разведчик',hands:['sword','empty'],armor:'Кожаная броня',ac:11,weapon:'shortsword',items:['Короткий меч · 1d6','Кожаная броня','Воровские инструменты','Рюкзак','Верёвка · 15 м','Рационы · 5 дней']},{name:'Городской плут',hands:['sword','empty'],armor:'Кожаная броня',ac:11,weapon:'shortsword',items:['Короткий меч · 1d6','Кожаная броня','Воровские инструменты','Рюкзак','Мел','Одеяло']}]},wizard:{name:'Маг',kind:1,die:6,priority:['int','con','dex','wis','cha','str'],skills:['arcana','investigation'],saves:['int','wis'],hint:'Интеллект — заклинания, Ловкость — защита.',kits:[{name:'Ученик',hands:['staff','empty'],armor:'Одежда',ac:10,weapon:'firebolt',items:['Обычный посох · 1d6','Книга заклинаний','Магический фокус','Рюкзак','Чернила и перо','Рационы · 5 дней']},{name:'Странствующий маг',hands:['staff','empty'],armor:'Одежда',ac:10,weapon:'firebolt',items:['Обычный посох · 1d6','Книга заклинаний','Магический фокус','Рюкзак','Одеяло','Верёвка · 15 м']}]},cleric:{name:'Жрец',kind:1,die:8,priority:['wis','con','str','dex','cha','int'],skills:['medicine','persuasion'],saves:['wis','cha'],hint:'Мудрость — заклинания и лечение.',kits:[{name:'Хранитель',hands:['staff','empty'],armor:'Кольчужная рубаха',ac:13,weapon:'mace',items:['Булава · 1d6','Кольчужная рубаха','Священный символ','Рюкзак','Бинты','Рационы · 5 дней']},{name:'Паломник',hands:['staff','empty'],armor:'Кольчужная рубаха',ac:13,weapon:'mace',items:['Булава · 1d6','Кольчужная рубаха','Священный символ','Рюкзак','Одеяло','Набор для разведения огня']}]}};
export function preset(id){const out={};CLASSES[id].priority.forEach((k,i)=>out[k]=ARRAY[i]);return out;}
export function validate(d){if(!d||!CLASSES[d.classId])throw Error('Выберите класс.');if(typeof d.name!=='string'||!d.name.trim()||d.name.trim().length>24)throw Error('Имя: от 1 до 24 символов.');if(Object.keys(d.stats||{}).sort().join()!=Object.keys(LABELS).sort().join()||pointsUsed(d.stats)>POINT_BUDGET)throw Error('Характеристики должны быть целыми числами от 8 до 15. Бюджет — 27 очков.');for(const k of Object.keys(COLORS))if(!COLORS[k].includes(d.appearance?.[k]))throw Error('Выберите внешний вид.');if(!['short','long','bald'].includes(d.appearance.hairStyle)||!['soft','stern','beard'].includes(d.appearance.face))throw Error('Выберите лицо и причёску.');if(!Number.isInteger(d.kit)||!CLASSES[d.classId].kits[d.kit])throw Error('Выберите комплект.');if(typeof d.background!=='string'||d.background.length<30||d.background.length>1800)throw Error('Создайте предысторию.');}
export function sheet(d,id){validate(d);const c=CLASSES[d.classId],kit=c.kits[d.kit],stats={...d.stats},mod=n=>Math.floor((n-10)/2),ac=kit.ac+(d.classId==='fighter'?0:d.classId==='cleric'?Math.min(2,mod(stats.dex)):mod(stats.dex));return{id,name:d.name.trim(),genitive:d.name.trim(),classId:d.classId,className:c.name,kind:c.kind,stats,appearance:{...d.appearance},background:d.background,inventory:[...kit.items],kit:d.kit,level:1,xp:0,gold:0,hitDie:c.die,max:c.die+mod(stats.con),hp:c.die+mod(stats.con),armorAC:ac,ac:ac+(kit.hands.includes('shield')?2:0),baseAC:ac+(kit.hands.includes('shield')?2:0),hands:[...kit.hands],weapon:kit.weapon,skills:[...c.skills],saves:[...c.saves],slots:['wizard','cleric'].includes(d.classId)?2:0,maxSlots:['wizard','cleric'].includes(d.classId)?2:0,secondWind:d.classId==='fighter'?2:0,maxSecondWind:d.classId==='fighter'?2:0,hitDice:1,maxHitDice:1,conditions:[],death:{success:0,failure:0,stable:false},concentration:null,torches:0,torch:false,darkvision:0,speed:6,move:6,facing:2,acted:false,bonusUsed:false,reactionUsed:false,confirmed:true};}
export function background(id,pick){const origin=['из маленького речного поселения','из шумного торгового города','из поселения у горного перевала','из старого монастырского предместья'][pick(4)],event=['исчезновение близкого человека','пожар, уничтоживший семейный дом','письмо с незнакомой печатью','пропажу важной семейной реликвии'][pick(4)],friend=['ремесленник Орен','лекарка Тея','старый наставник Марен','торговка Лиса'][pick(4)];const training={fighter:'Годы службы научили тебя держать строй и защищать товарищей.',rogue:'Ты научился замечать тайники, читать людей и находить обходные пути.',wizard:'Обучение магии дало тебе первые заклинания и привычку проверять непонятное.',cleric:'Помогая людям при храме, ты обрёл веру и первые силы исцеления.'}[id];return `Ты родом ${origin}. ${training} В дорогу тебя привело ${event}. Твой старый знакомый — ${friend}; однажды этот человек помог тебе, и ты помнишь свой долг. Твоя цель — узнать правду и найти место, которое сможешь назвать домом.`;}
